### ISSUE TITLE
Support other types and formats 

### ISSUE THREAD

**Issue by marcjulianschwarz** [Noamko/QuickLaTeX#1]
Hey @Noamko. I'd like to contribute some code to support other types and formats like the ones shown below. Is QuickLaTeX still maintained such that the changes would make it to the Raycast store? I am asking as I would profit a lot from the new functionality.

<img width="918" alt="CleanShot 2023-09-11 at 10 36 45@2x" src="https://github.com/Noamko/QuickLaTeX/assets/67844154/d6cf86a2-ad1e-49da-b91c-bb909e3c7336">

**Comment by Noamko** [comment]
Yes definitely! feel free to open a PR, and ill be happy to include it.

**Comment by Noamko** [comment]
> Hey @Noamko. I'd like to contribute some code to support other types and formats like the ones shown below. Is QuickLaTeX still maintained such that the changes would make it to the Raycast store? I am asking as I would profit a lot from the new functionality.
> 
> <img alt="CleanShot 2023-09-11 at 10 36 45@2x" width="918" src="https://user-images.githubusercontent.com/67844154/266959753-d6cf86a2-ad1e-49da-b91c-bb909e3c7336.png">

Yes definitely! feel free to open a PR, and ill be happy to include it.
